### ISSUE TITLE
列数字过长后，直接打开excel表列宽需要手动调整

### ISSUE THREAD

**Issue by kevin-xhh** [gupeng1978/tools#2]
现象如下图所示：
![image](https://github.com/gupeng1978/tools/assets/60497006/0f15ab86-7027-4624-8c27-28d389a49d12)

手动调整后：
![image](https://github.com/gupeng1978/tools/assets/60497006/17465c4f-fe63-4264-b3d4-5c3506f64308)

**Comment by gupeng1978** [comment]
@kevin-xhh bug已经修复，支持数字位宽计算，请update到v0.3.2版本试一下(python -m pip install xlsx-ptable==0.3.2。
