### ISSUE TITLE
2个log文件合并表格时，最终的输出只显示2个log文件共同的行

### ISSUE THREAD

**Issue by wutongkunliuman** [gupeng1978/tools#3]
使用仓库中原有的sample6-1.log和 sample6-2.log， 在sample6-2.log中增加下面的两行：
#tab_nnp: (model@resnet34), (thread@1), (step@copyH2D),  (pcie.ms@6.4),
#tab_nnp: (model@resnet34), (thread@1), (step@copyD2H),  (pcie.ms@8.2),

执行：
wutongkun@wutongkun-B460MDS3HV2:~/tools/xlsx_ptable/sample$ python3 sample.py 
输出的excel表格没有sample6-2.log中增加的两行：
![微信图片_20230830090010](https://github.com/gupeng1978/tools/assets/38294379/019c289d-383b-4e38-acf2-58205d6eb5c2)

**Comment by gupeng1978** [comment]
@wutongkunliuman bug已经修复，根源在于log2比log1的record内容多，导致合并会丢失，最新的0.3.4已经修复。python -m pip install xlsx-ptable==0.3.4更新。
